export function matchErrors([source, error]: [string, Error], [expectedSource, expectedErrorMessage]: [string, string]) {
    return source === expectedSource &&
        error.message.includes(expectedErrorMessage);
}

// A list of known errors. During API parsing, we check that these errors (no more, no less) are thrown, to ensure that
// we're aware of all current issues. Where possible of course it's better to either get the issue fixed in the spec
// upstream, or patch the spec ourselves before parsing, but these are remaining examples where that's difficult.
export const KNOWN_ERRORS = {
    // Fails due to a bad x-ms-odata internal reference:
    "node_modules/openapi-directory/APIs/azure.com/azsadmin-RegionHealth/2016-05-01/swagger.yaml": "Could not resolve reference #/definitions/Alert",

    // A $ref to a key that's a number with an underscore, which is parsed wrong due to:
    // https://github.com/nodeca/js-yaml/issues/627
    "node_modules/openapi-directory/APIs/statsocial.com/1.0.0/openapi.yaml": "Token \"18_24\" does not exist.",

    // A few specs with $ref links to `null` properties, which fails due to:
    // https://github.com/APIDevTools/json-schema-ref-parser/issues/310
    "node_modules/openapi-directory/APIs/personio.de/personnel/1.0/openapi.yaml": "Token \"comment\" does not exist.",
    "node_modules/openapi-directory/APIs/rebilly.com/2.1/openapi.yaml": "Token \"feature\" does not exist.",
    "node_modules/openapi-directory/APIs/viator.com/1.0.0/openapi.yaml": "Token \"pas\" does not exist.",

    // Lots of Azure specs that reference external files which don't exist:
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2016-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2017-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2017-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2017-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2017-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2017-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2018-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2018-01-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2018-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2018-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2018-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCircuit/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCrossConnection/2018-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCrossConnection/2018-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCrossConnection/2018-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCrossConnection/2018-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCrossConnection/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCrossConnection/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCrossConnection/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCrossConnection/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-expressRouteCrossConnection/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-interfaceEndpoint/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-interfaceEndpoint/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-interfaceEndpoint/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-interfaceEndpoint/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-interfaceEndpoint/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2016-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2015-06-15/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2017-03-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2017-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2016-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2017-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2017-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2018-01-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2017-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2018-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2017-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2018-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2018-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2018-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2019-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2016-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2019-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2015-06-15/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2019-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-loadBalancer/2019-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2016-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2017-03-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2017-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2017-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2017-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2017-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2017-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkProfile/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkInterface/2018-01-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkProfile/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkProfile/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkProfile/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkProfile/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkProfile/2019-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkProfile/2019-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkProfile/2019-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkProfile/2019-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2016-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2017-03-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2015-06-15/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2017-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2016-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2017-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2017-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2017-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2018-01-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2018-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2017-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2018-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2018-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2018-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2019-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2019-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2019-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-networkSecurityGroup/2019-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-privateEndpoint/2019-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-privateEndpoint/2019-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-privateEndpoint/2019-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-privateEndpoint/2019-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2016-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2015-06-15/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2016-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2017-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2017-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2017-03-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2017-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2017-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2017-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2018-01-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2018-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2018-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2018-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2018-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2019-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2019-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2019-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-publicIpAddress/2019-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2017-03-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2017-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2017-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2017-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2016-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2017-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2018-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2018-01-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2018-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2017-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2018-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2018-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeFilter/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2016-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2015-06-15/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2017-03-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2016-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2017-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2017-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2017-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2018-01-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2017-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2017-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2018-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2018-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2018-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2018-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2019-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2019-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2019-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-routeTable/2019-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-serviceEndpointPolicy/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-serviceEndpointPolicy/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-serviceEndpointPolicy/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-serviceEndpointPolicy/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-serviceEndpointPolicy/2019-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-serviceEndpointPolicy/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-serviceEndpointPolicy/2019-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-serviceEndpointPolicy/2019-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-serviceEndpointPolicy/2019-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2015-06-15/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2016-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2016-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2017-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2017-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2017-03-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2017-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2017-09-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2018-01-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2017-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2018-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2018-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2018-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2018-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2019-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2019-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2019-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetwork/2019-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetworkTap/2018-10-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetworkTap/2018-11-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetworkTap/2018-12-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetworkTap/2018-08-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetworkTap/2019-02-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetworkTap/2019-04-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetworkTap/2019-07-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetworkTap/2019-06-01/swagger.yaml": "Error opening file",
    "node_modules/openapi-directory/APIs/azure.com/network-virtualNetworkTap/2019-08-01/swagger.yaml": "Error opening file"
};