name: CI
on: push
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci --unsafe-perm # Unsafe required for napa in CI
      - run: npm test # Test the code itself
      - run: npm run build # Confirm that the API specs & index builds successfully