name: CI
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci

      # Check that the tests and overall build all still pass
      - run: npm test
      - run: npm run build